### ISSUE TITLE
Some examples don't work without pi?

### ISSUE THREAD

**Issue by tamaspolgar** [lachatak/pi4j-client#3]
_running listenGpioExample and triggerGpioExample_

[error] Oct 23, 2015 9:04:06 PM com.pi4j.util.NativeLibraryLoader load
[error] SEVERE: Unable to load [libpi4j.so] using path: [/lib/libpi4j.so]
[error] java.lang.UnsatisfiedLinkError: /private/var/folders/Tw/Tw+-QCR-GAeOeEMW1bpwfE+++TI/-Tmp-/libpi4j7140806274011122291.so: dlopen(/private/var/folders/Tw/Tw+-QCR-GAeOeEMW1bpwfE+++TI/-Tmp-/libpi4j7140806274011122291.so, 1): no suitable image found.  Did find:
[error]     /private/var/folders/Tw/Tw+-QCR-GAeOeEMW1bpwfE+++TI/-Tmp-/libpi4j7140806274011122291.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00
[error]     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[error]     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
[error]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
[error]     at java.lang.Runtime.load0(Runtime.java:809)
[error]     at java.lang.System.load(System.java:1086)
[error]     at com.pi4j.util.NativeLibraryLoader.loadLibraryFromClasspath(NativeLibraryLoader.java:143)
[error]     at com.pi4j.util.NativeLibraryLoader.load(NativeLibraryLoader.java:92)
[error]     at com.pi4j.wiringpi.GpioInterrupt.<clinit>(GpioInterrupt.java:72)
[error]     at com.pi4j.io.gpio.RaspiGpioProvider.updateInterruptListener(RaspiGpioProvider.java:231)
[error]     at com.pi4j.io.gpio.RaspiGpioProvider.addListener(RaspiGpioProvider.java:216)
[error]     at com.pi4j.io.gpio.impl.GpioPinImpl.updateInterruptListener(GpioPinImpl.java:403)
[error]     at com.pi4j.io.gpio.impl.GpioPinImpl.addTrigger(GpioPinImpl.java:492)
[error]     at org.kaloz.pi4j.client.examples.TriggerGpioExample$.delayedEndpoint$org$kaloz$pi4j$client$examples$TriggerGpioExample$1(TriggerGpioExample.scala:22)
[error]     at org.kaloz.pi4j.client.examples.TriggerGpioExample$delayedInit$body.apply(TriggerGpioExample.scala:8)
[error]     at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]     at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]     at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error]     at scala.App$class.main(App.scala:76)
[error]     at org.kaloz.pi4j.client.examples.TriggerGpioExample$.main(TriggerGpioExample.scala:8)
[error]     at org.kaloz.pi4j.client.examples.TriggerGpioExample.main(TriggerGpioExample.scala)
[error] 

and...

[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] INFO: hook_get_auto_repeat_rate [107]: IOHIDGetParameter: 75.
[error] 
[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] INFO: hook_get_auto_repeat_delay [189]: IOHIDGetParameter: 450.
[error] 
[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] WARNING: jni_SetProperties [116]: Invalid result returned from hook_get_pointer_acceleration_multiplier()!
[error] 
[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] WARNING: jni_SetProperties [146]: Invalid result returned from hook_get_pointer_acceleration_threshold()!
[error] 
[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] WARNING: jni_SetProperties [176]: Invalid result returned from hook_get_pointer_sensitivity()!
[error] 
[error] Oct 23, 2015 9:04:06 PM java.lang.ClassLoader$NativeLibrary load
[error] INFO: hook_get_multi_click_time [399]: IOHIDGetParameter: 450.
[error] 
[error] Oct 23, 2015 9:04:07 PM org.jnativehook.GlobalScreen$NativeHookThread enable
[error] SEVERE: hook_run [1150]: Accessibility API is disabled!
[error] 

and:

[error] java.lang.ExceptionInInitializerError
[error]     at org.kaloz.pi4j.client.console.StubClientActor$$anonfun$handle$1.applyOrElse(ConsoleClientActor.scala:74)
[error]     at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[error]     at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:190)
[error]     at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[error]     at org.kaloz.pi4j.client.console.StubClientActor.aroundReceive(ConsoleClientActor.scala:15)
[error]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[error]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[error]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[error]     at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[error]     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: org.jnativehook.NativeHookException: Failed to enable access for assistive devices.
[error]     at org.jnativehook.GlobalScreen$NativeHookThread.enable(Native Method)
[error]     at org.jnativehook.GlobalScreen$NativeHookThread.run(Unknown Source)

**Comment by lachatak** [comment]
Is jnativehook working correctly on Mac? 
http://worksnaps.freshdesk.com/support/solutions/articles/142505-how-to-enable-accessibility-on-mac-osx-10-9-mavericks-and-10-10-yosemite-

**Comment by tamaspolgar** [comment]
I made it working, I just had to enable accesibility. All good ;)
