### ISSUE TITLE
Make WiringPiSetupResponse usable

### ISSUE THREAD

**Issue by tamaspolgar** [lachatak/pi4j-client#6]
In org.kaloz.pi4j.client.actor.InMemoryClientActor, we're sending WiringPiSetupResponse(0) dummy message.

Can we add the pins: Map[Int, Pin] to it? Maybe some simplified version of the Pins.

**Comment by lachatak** [comment]
I don't want to add pins as they will be added when they are exported. There is no point in adding any pins as long as it is not exported. Normally I suppose it is a hardware initialisation.  But I am open to add  any meaning full functionality.

**Comment by tamaspolgar** [comment]
I can use the PinStatesResponse, it's fine.
